/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.kafka;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Key;
import com.google.inject.name.Names;
import io.undertow.Handlers;
import io.undertow.Undertow;
import io.undertow.server.HttpHandler;

public class App {
    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new KafkaModule());
        HttpHandler receiver = injector.getInstance(Key.get(HttpHandler.class, Names.named("receiver")));
        HttpHandler root = Handlers.routing().post("/", receiver);
        Undertow.builder()
                .addHttpListener(8888, "0.0.0.0")
                .setHandler(root)
                .build()
                .start();
    }
}
